#!/usr/bin/env python3

# External
import argparse
import rospy

from roslabware_drivers.ika_rct_digital import RCTDigitalHotplateRos

if __name__ == "__main__":
    # Get arguments needed
    parser = argparse.ArgumentParser(
        prog="IKA RCT digital hotplate ROS",
        description='ROS node for an IKA RCT Digital hotplate device')
    parser.add_argument(
        '-d',
        '--device_name',
        action='store',
        default='rct_ika_hotplate',
        nargs='?',
        const=1,
        help='Device name')
    parser.add_argument(
        '-c',
        '--connection_mode',
        action='store',
        default='serial',
        nargs='?',
        const=1,
        help='Connection mode: "tcpip", "serial" or "http"')
    parser.add_argument(
        '-add',
        '--address',
        action='store',
        default='None',
        nargs='?',
        const=1,
        help='IP Address.')
    parser.add_argument(
        '-p',
        '--port',
        action='store',
        default='/dev/ttyACM0',
        nargs='?',
        const=1,
        help='Serial or TCP/IP port')
    parser.add_argument(
        '-s',
        '--sensor',
        action='store',
        default='0',
        nargs='?',
        const=1,
        help='Temperature sensor:\
                0: internal, 1: external')
    parser.add_argument(
        '-l',
        '--simulation',
        action='store',
        nargs='?',
        const=1,
        default='False',
        help='Simulation mode or not (bool)')

    args, unknown = parser.parse_known_args()

    # Initialize rospy node
    rospy.init_node("RCTDigitalHotplate Driver", anonymous=True)

    # Object oriented initialization for ROS
    hotplate_ret_ika = RCTDigitalHotplateRos(
        device_name=args.device_name,
        connection_mode=args.connection_mode,
        address=args.address,
        port=args.port,
        sensor=int(args.sensor),
        simulation=args.simulation)

    # Stop everything on shutdown
    rospy.on_shutdown(hotplate_ret_ika.stop_heating())
    rospy.on_shutdown(hotplate_ret_ika.stop_stirring())
    rospy.spin()
