#!/usr/bin/env python3

# External
import sys
import rospy
from roslabware_drivers.ika_ret_control_visc import RETControlViscHotplateRos

# Object oriented initialization for ROS
if __name__ == "__main__":
    if len(sys.argv) > 1:
        serial_port = sys.argv[1]
    else:
        serial_port = '/dev/ttyACM0'
        rospy.logwarn('No port provided. Using ttyUSB0 as default port')

    # Initialize rospy node
    rospy.init_node("RETControlViscHotplate Driver", anonymous=True)

    # Create instance
    hotplate_ret_ika = RETControlViscHotplateRos(
        device_name=None,
        connection_mode='serial',
        address=None,
        port=serial_port)

    # Stop everything on shutdown
    rospy.on_shutdown(hotplate_ret_ika.stop_heating())
    rospy.on_shutdown(hotplate_ret_ika.stop_stirring())
    rospy.spin()
