#!/usr/bin/env python3

# External
import argparse
import rospy

from roslabware_drivers.kern_pcb2500 import PCB2500Ros

if __name__ == "__main__":
    # Get arguments needed
    parser = argparse.ArgumentParser(
        prog="Kern Top balance ROS",
        description='ROS node for a Kern Top balance')
    parser.add_argument(
        '-bd',
        '--b_device_name',
        action='store',
        default='rct_ika_hotplate',
        nargs='?',
        const=1,
        help='Device name')
    parser.add_argument(
        '-bc',
        '--b_connection_mode',
        action='store',
        default='serial',
        nargs='?',
        const=1,
        help='Connection mode: "tcpip", "serial" or "http"')
    parser.add_argument(
        '-badd',
        '--b_address',
        action='store',
        default='None',
        nargs='?',
        const=1,
        help='IP Address.')
    parser.add_argument(
        '-bp',
        '--b_port',
        action='store',
        default='COM12',
        nargs='?',
        const=1,
        help='Serial or TCP/IP port')

    parser.add_argument(
        '-bl',
        '--b_simulation',
        action='store',
        nargs='?',
        const=1,
        default='False',
        help='Simulation mode or not (bool)')

    args, unknown = parser.parse_known_args()

    # Initialize ROS node
    rospy.init_node("Kern_PCB2500_Driver", anonymous=True)

    # Objectoriented initialization of ROS
    kern_ros = PCB2500Ros(
        device_name=args.b_device_name,
        connection_mode=args.b_connection_mode,
        address=args.b_address,
        port=args.b_port,
        simulation=args.b_simulation)

    rospy.loginfo("Kern balance roslabware driver started")
    rospy.spin()