#!/usr/bin/env python3

# External
import argparse
import rospy

from roslabware_drivers.knf_simdos10_rcplus import RCPlusRos

if __name__ == "__main__":
    # Get arguments needed
    parser = argparse.ArgumentParser(
        prog="KNF RC-Plus diaphragm pump ROS",
        description='ROS node for RC-Plus diaphragm pump')
    parser.add_argument(
        '-knfd',
        '--knf_device_name',
        action='store',
        default='knf_rcplus_diaphragm_pump',
        nargs='?',
        const=1,
        help='Device name')
    parser.add_argument(
        '-knfc',
        '--knf_connection_mode',
        action='store',
        default='serial',
        nargs='?',
        const=1,
        help='Connection mode: "tcpip", "serial" or "http"')
    parser.add_argument(
        '-knfadd',
        '--knf_address',
        action='store',
        default='None',
        nargs='?',
        const=1,
        help='IP Address.')
    parser.add_argument(
        '-knfp',
        '--knf_port',
        action='store',
        default='COM13',
        nargs='?',
        const=1,
        help='Serial or TCP/IP port')
    parser.add_argument(
        '-knfswa',
        '--knf_switch_address',
        action='store',
        default='00',
        nargs='?',
        const=1,
        help='Switch address on the back of the pump')
    parser.add_argument(
        '-knfl',
        '--knf_simulation',
        action='store',
        nargs='?',
        const=1,
        default='False',
        help='Simulation mode or not (bool)')

    args, unknown = parser.parse_known_args()

    # Initialize rospy node
    rospy.init_node("KNF RC-Plus syringe pump driver", anonymous=True)

    # Object oriented initialization for ROS
    diaphragm_pump = RCPlusRos(
        device_name=args.knf_device_name,
        connection_mode=args.knf_connection_mode,
        address=args.knf_address,
        port=args.knf_port,
        switch_address=args.knf_switch_address,
        simulation=args.knf_simulation)

    # Stop everything on shutdown
    rospy.on_shutdown(diaphragm_pump.stop())
    rospy.spin()