#!/usr/bin/env python3

# external
import rospy
import sys
from roslabware_drivers.mettler_quantos_qb1 import QuantosQB1Ros

# Object oriented initialization for ROS
if __name__ == "__main__":

    # Set default port if not provided
    if len(sys.argv) > 1:
        serial_port = sys.argv[1]
    else:
        serial_port = '/dev/ttyUSB0'
        rospy.logwarn('No port provided. Using ttyUSB0 as default port')

    # Initiliaze rospy node
    rospy.init_node("QuantosQB1 Driver", anonymous=True)

    # Create instance of ROS Wrapper
    Quantos_ROS = QuantosQB1Ros(
            device_name=None,
            connection_mode='serial',
            address=None,
            port=serial_port,
            simulation=True)

    # Keeps python from exiting until node is stopped
    rospy.spin()
