#!/usr/bin/env python3

# External
import argparse
import rospy

from roslabware_drivers.sash_door import SashDoorRos

if __name__ == "__main__":
    # Get arguments needed
    parser = argparse.ArgumentParser(
        prog="Sash Door ROS",
        description='ROS node for a fumehood sash door')
    parser.add_argument(
        '-sd',
        '--s_name',
        action='store',
        default='sash_door',
        nargs='?',
        const=1,
        help='Device name')
    parser.add_argument(
        '-sc',
        '--s_connection_mode',
        action='store',
        default='serial',
        nargs='?',
        const=1,
        help='Connection mode: "tcpip", "serial" or "http"')
    parser.add_argument(
        '-sadd',
        '--s_address',
        action='store',
        default='None',
        nargs='?',
        const=1,
        help='IP Address.')
    parser.add_argument(
        '-sp',
        '--s_port',
        action='store',
        default='COM5',
        nargs='?',
        const=1,
        help='Serial or TCP/IP port')

    parser.add_argument(
        '-ss',
        '--s_simulation',
        action='store',
        nargs='?',
        const=1,
        default='False',
        help='Simulation mode or not (bool)')

    args, unknown = parser.parse_known_args()

    # Initialize ROS node
    rospy.init_node("sash_door_driver", anonymous=True)

    # Objectoriented initialization of ROS
    sash_ros = SashDoorRos(
        device_name=args.s_name,
        connection_mode=args.s_connection_mode,
        address=args.s_address,
        port=args.s_port,
        simulation=args.s_simulation)

    rospy.loginfo("Sash door roslabware driver started")
    rospy.spin()