#!/usr/bin/env python3

# External
import argparse
import rospy

from roslabware_drivers.sash_door import SashDoorRos

if __name__ == "__main__":
    # Get arguments needed
    parser = argparse.ArgumentParser(
        prog="Sash Door ROS",
        description='ROS node for a fumehood sash door')
    parser.add_argument(
        '-d',
        '--Door_name',
        action='store',
        default='sash_door',
        nargs='?',
        const=1,
        help='Device name')
    parser.add_argument(
        '-c',
        '--Door_connection_mode',
        action='store',
        default='serial',
        nargs='?',
        const=1,
        help='Connection mode: "tcpip", "serial" or "http"')
    parser.add_argument(
        '-add',
        '--Door_address',
        action='store',
        default='None',
        nargs='?',
        const=1,
        help='IP Address.')
    parser.add_argument(
        '-p',
        '--Door_port',
        action='store',
        default='/dev/ttyACM0',
        nargs='?',
        const=1,
        help='Serial or TCP/IP port')

    parser.add_argument(
        '-s',
        '--Door_simulation',
        action='store',
        nargs='?',
        const=1,
        default='False',
        help='Simulation mode or not (bool)')

    args, unknown = parser.parse_known_args()

    # Initialize ROS node
    rospy.init_node("sash_door_driver", anonymous=True)

    # Objectoriented initialization of ROS
    sash_ros = SashDoorRos(
        device_name=args.Door_name,
        connection_mode=args.Door_connection_mode,
        address=args.Door_address,
        port=args.Door_port,
        simulation=args.Door_simulation)

    rospy.loginfo("sash door roslabware driver started")
    rospy.spin()