#!/usr/bin/env python3

# External
import argparse
import rospy

from roslabware_drivers.sash_and_balance_door import SashBalanceDoorRos

if __name__ == "__main__":
    # Get arguments needed
    parser = argparse.ArgumentParser(
        prog="Sash and Balance Door ROS",
        description='ROS node for fumehood sash door and balance door')
    parser.add_argument(
        '-sd',
        '--s_name',
        action='store',
        default='sash_and_balance_door',
        nargs='?',
        const=1,
        help='Device name')
    parser.add_argument(
        '-sc',
        '--s_connection_mode',
        action='store',
        default='serial',
        nargs='?',
        const=1,
        help='Connection mode: "tcpip", "serial" or "http"')
    parser.add_argument(
        '-sadd',
        '--s_address',
        action='store',
        default='None',
        nargs='?',
        const=1,
        help='IP Address.')
    parser.add_argument(
        '-sp',
        '--s_port',
        action='store',
        default='COM15',
        nargs='?',
        const=1,
        help='Serial or TCP/IP port')

    parser.add_argument(
        '-ss',
        '--s_simulation',
        action='store',
        nargs='?',
        const=1,
        default='False',
        help='Simulation mode or not (bool)')

    args, unknown = parser.parse_known_args()

    # Initialize ROS node
    rospy.init_node("sash_and_balance_door_driver", anonymous=True)

    # Objectoriented initialization of ROS
    sash_ros = SashBalanceDoorRos(
        device_name=args.s_name,
        connection_mode=args.s_connection_mode,
        address=args.s_address,
        port=args.s_port,
        simulation=args.s_simulation)

    rospy.loginfo("Sash and balance door roslabware driver started")
    rospy.spin()