#!/usr/bin/env python3

# External
import argparse
import rospy

from roslabware_drivers.tecan_xlp6000 import XLP6000Ros

if __name__ == "__main__":
    # Get arguments needed
    parser = argparse.ArgumentParser(
        prog="XLP syrnge pump ROS",
        description='ROS node for XLP6000 syringe pump')
    parser.add_argument(
        '-d',
        '--device_name',
        action='store',
        default='rct_ika_hotplate',
        nargs='?',
        const=1,
        help='Device name')
    parser.add_argument(
        '-c',
        '--connection_mode',
        action='store',
        default='serial',
        nargs='?',
        const=1,
        help='Connection mode: "tcpip", "serial" or "http"')
    parser.add_argument(
        '-add',
        '--address',
        action='store',
        default='None',
        nargs='?',
        const=1,
        help='IP Address.')
    parser.add_argument(
        '-p',
        '--port',
        action='store',
        default='/dev/ttyACM0',
        nargs='?',
        const=1,
        help='Serial or TCP/IP port')
    parser.add_argument(
        '-swa',
        '--switch_address',
        action='store',
        default='0',
        nargs='?',
        const=1,
        help='Switch address on the back of the pump')
    parser.add_argument(
        '-size',
        '--syringe_size',
        action='store',
        nargs='?',
        const=1,
        help='Syringe size in mL')

    args = parser.parse_args()

    # Initialize rospy node
    rospy.init_node("Tecan XLP600 syringe pymp driver", anonymous=True)

    # Object oriented initialization for ROS
    syringe_pump = XLP6000Ros(
        device_name=args.device_name,
        connection_mode=args.connection_mode,
        address=args.address,
        port=args.port,
        syringe_size=args.syringe_size,
        switch_address=args.switch_address)

    # Stop everything on shutdown
    rospy.on_shutdown(syringe_pump.stop())
    rospy.spin()
