#!/usr/bin/env python

""" Script to use the Mettler Toledo Quantos dispensing system with ROS """

# external
import rospy
import sys

# local
from ....pylabware.devices.quantos_solid_dispenser import Quantos

# Object oriented initialization for ROS
if __name__ == "__main__":

    # Set default port if not provided
    if len(sys.argv) > 1:
        serial_port = sys.argv[1]
    else:
        serial_port = '/dev/ttyUSB0'
        rospy.logwarn('No port provided. Setting ttyUSB0')

    # Initiliaze rospy node
    rospy.init_node("Quantos_Driver", anonymous=True)

    # Create instance of ROS Wrapper
    Quantos_ROS = Quantos(
            device_name=None,
            connection_mode='serial',
            address=None,
            port=serial_port)

    # Spin ros??
    rospy.spin()
