# Available commands to use the MT Quantos System
int32 START_DOSE = 0
int32 STOP_DOSE = 1
int32 GET_DOOR_POS = 2
int32 GET_SAMPLE_POS = 3 #
int32 GET_HEAD_DATA = 4
int32 GET_SAMPLE_DATA = 5 #
int32 LOCK_PIN = 6
int32 UNLOCK_PIN = 7
int32 OPEN_DOOR = 8
int32 CLOSE_DOOR = 9
int32 SET_SAMPLE_POS = 10 #
int32 SET_TAP_BEFORE = 11 #
int32 SET_TAP_DURING = 12 #
int32 SET_TAP_INT = 13 #
int32 SET_TAP_DURATION = 14 #
int32 SET_TARGET = 15
int32 SET_TOL = 16
int32 SET_TOL_MODE = 17
int32 SET_SAMPLE_ID = 18 #
int32 SET_PAN_OFF = 19
int32 SET_ALG = 20 #
int32 SET_AS_ON = 21
int32 SET_AS_OFF = 22
int32 DISPENSE_SOLID = 23
int32 TARE = 24
int32 GET_STABLE_WEIGHT = 25

int32 quantos_command
string quantos_ID
bool quantos_bool
float32 quantos_float
int32 quantos_int
