# Available commands to use the MT Quantos System
int32 START_DOSE = 0
int32 STOP_DOSE = 1
int32 GET_DOOR_POS = 2
int32 GET_SAMPLE_POS = 3
int32 GET_HEAD_DATA = 4
int32 GET_SAMPLE_DATA = 5
int32 MOVE_PIN = 6
int32 OPEN_DOOR = 7
int32 CLOSE_DOOR = 8
int32 SET_SAMPLE_POS = 9
int32 SET_TAP_BEFORE = 10
int32 SET_TAP_DURING = 11
int32 SET_TAP_INT = 12
int32 SET_TAP_DURATION = 13
int32 SET_TARGET = 14
int32 SET_TOL = 15
int32 SET_TOL_MODE = 16
int32 SET_SAMPLE_ID = 17
int32 SET_PAN_OFF = 18
int32 SET_ALG = 19
int32 SET_AS = 20
int32 DISPENSE_SOLID = 21

int32 quantos_command
string quantos_ID
bool quantos_bool
float32 quantos_float
int32 quantos_int
